### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ghost** [RanzTm/Registreerimise-vorm-IS-13-#1]
1) Sytle lisatakse üldjuhul niimoodi bootstrapi oma
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">`

2) kustuta.php võiks olla kergemini üles ehitatud

3) ajaväli katkine

**Comment by RanzTm** [comment]
Töö parandatud, kõik on korras!

**Comment by ragnarkurm** [comment]
1) iga konkreetne probleem peaks olema eraldi issue. siis saab iga probleemi eraldi kommentaarida ning jälgida nende ajalugu. Lisaks veel kui siduda commit issue-ga, siis kuidas sa saad aru, mis mille kohta käib?

2) "kustuta.php võiks olla kergemini üles ehitatud" -- liiga üldine. Minu jaoks ei tähenda mitte midagi.

3) "ajaväli katkine" - mida see tähendab? millisel lehel see ei tööta? milles väljendub mittetöötamine?

**Comment by ragnarkurm** [comment]
Kui issue on valmis, siis staatuseks tuleks closed panna.

Kui teed uuendusi, koodi, siis pane commit message, ka. Muidu on ajaloost peaaegu võimatu aru saada, mida ja miks on tehtud. Kas need on mingi issuega seotud? vms. Näiteks:

```
git add edit.php
git commit -m 'kustutasin kasutaja muutmise vormist liigse välja ära.'
git push
```
